// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: protocol/proto/medianprice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 MedianPrice 消息和包含多个 MedianPrice 的消息
type MedianPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin  string  `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`     // 对应 Coin 字段
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` // 对应 Price 字段
}

func (x *MedianPrice) Reset() {
	*x = MedianPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_medianprice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedianPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedianPrice) ProtoMessage() {}

func (x *MedianPrice) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_medianprice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedianPrice.ProtoReflect.Descriptor instead.
func (*MedianPrice) Descriptor() ([]byte, []int) {
	return file_protocol_proto_medianprice_proto_rawDescGZIP(), []int{0}
}

func (x *MedianPrice) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *MedianPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type MedianPriceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prices []*MedianPrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"` // 包含多个 MedianPrice 的数组
}

func (x *MedianPriceList) Reset() {
	*x = MedianPriceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_medianprice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedianPriceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedianPriceList) ProtoMessage() {}

func (x *MedianPriceList) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_medianprice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedianPriceList.ProtoReflect.Descriptor instead.
func (*MedianPriceList) Descriptor() ([]byte, []int) {
	return file_protocol_proto_medianprice_proto_rawDescGZIP(), []int{1}
}

func (x *MedianPriceList) GetPrices() []*MedianPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

var File_protocol_proto_medianprice_proto protoreflect.FileDescriptor

var file_protocol_proto_medianprice_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x06, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_proto_medianprice_proto_rawDescOnce sync.Once
	file_protocol_proto_medianprice_proto_rawDescData = file_protocol_proto_medianprice_proto_rawDesc
)

func file_protocol_proto_medianprice_proto_rawDescGZIP() []byte {
	file_protocol_proto_medianprice_proto_rawDescOnce.Do(func() {
		file_protocol_proto_medianprice_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_medianprice_proto_rawDescData)
	})
	return file_protocol_proto_medianprice_proto_rawDescData
}

var file_protocol_proto_medianprice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_proto_medianprice_proto_goTypes = []interface{}{
	(*MedianPrice)(nil),     // 0: MedianPrice
	(*MedianPriceList)(nil), // 1: MedianPriceList
}
var file_protocol_proto_medianprice_proto_depIdxs = []int32{
	0, // 0: MedianPriceList.prices:type_name -> MedianPrice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_proto_medianprice_proto_init() }
func file_protocol_proto_medianprice_proto_init() {
	if File_protocol_proto_medianprice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_medianprice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MedianPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_medianprice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MedianPriceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_medianprice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_medianprice_proto_goTypes,
		DependencyIndexes: file_protocol_proto_medianprice_proto_depIdxs,
		MessageInfos:      file_protocol_proto_medianprice_proto_msgTypes,
	}.Build()
	File_protocol_proto_medianprice_proto = out.File
	file_protocol_proto_medianprice_proto_rawDesc = nil
	file_protocol_proto_medianprice_proto_goTypes = nil
	file_protocol_proto_medianprice_proto_depIdxs = nil
}
